### ISSUE TITLE
Chrome + Polylines + Frames = Unstable Polyline Positions

### ISSUE THREAD

**Issue by pmascari** [mapstraction/mxn#100]
In Chrome, when loading a map in an iFrame and drawing polylines, it seems the origin of the map is getting messed up because lines are not drawn where they're supposed to be.  In addition, after dragging the map in any direction the polylines move and/or disappear.  This appears to only happen in Chrome and only when the map is in a frame.  It does _not_ occur in Firefox, IE, nor Safari.

Please see the thematic map of central, OH at the link, below.  In all browsers BUT Chrome the polygons load in the middle of the map and move accordingly as the map is zoomed and scrolled.  In Chrome, the lines are drawn, incorrectly, at top left and move or disappear as the map is moved.

http://www.sdsinc.com/chromeTest.cfm

**Comment by pmascari** [comment]
Upon further investigation this appears to be an issue with Cloudmade maps.

**Comment by gilesc50** [comment]
Ok so closing this issue
