### ISSUE TITLE
Is there a way to pass in options at init time with the constructor?

### ISSUE THREAD

**Issue by palewire** [mapstraction/mxn#102]
Say I wanted to prevent the default base layer from loading, for instance.

**Comment by brunob** [comment]
I haven't found a way to do it for now. I was thinking about it last week when i was needing to play with OpenLayers.ImgPath on an openlayers map (this setting need to be set befor the load of base layers). I think we should provide a way to do similar things...

**Comment by palewire** [comment]
This has come up for me in issue #97 and pull request #101. I'd like to provide a default base layer for the user, but I'd also like to give them the ability to "skip" it and load their own custom tile set instead.

**Comment by palewire** [comment]
Closing as stale.
