### ISSUE TITLE
Openlayers : addControls can't be used multiple time

### ISSUE THREAD

**Issue by brunob** [mapstraction/mxn#109]
The documentation says that addControls() can be used multiple times on the same map but it's not true with Openlayers. If you use addControls to add a first set of controls to the map and after that another set of controls, the first set is removed from the map. This is issue is not present with googlev3 APi for info.

The issue is due to that code :

https://github.com/mapstraction/mxn/blob/master/source/mxn.openlayers.core.js#L113

I don't know why we do that, but i think we should remove or refine the for loop. Reading the comment above the for loop make me think that the loop is there to allow removing all controls of the map when addControls() without any arguments...

**Comment by vicchi** [comment]
The documentation was way out of line with what each provider's implementation actually did. Some, like OpenLayers, removed all controls and then added in the controls passed to `addControls()`. Some never removed controls. Some never added controls. And all implementation didn't agree as to what the starting set of controls should be. Some? All? None?

So I've rationalised `addControls()` across all providers, wherever possible. The one exception is Microsoft v7 where the majority of controls can only be specified when the map is initially instantiated (genius of a design decision that).

The default map for all providers, excepting Microsoft 7, now shows no controls at all.

Calling `addControls({})` will clear all controls from the map.

Calling `addControls()` with a property list as the `args` parameter will add those controls specified and remove those which are omitted.

Calling `addControls()` multiple times is allowed and will change the visible controls according to the supplied arguments.

I'll update the documentation in `mxn.core.js` to reflect this as part of a general documentation clean and polish.
