### ISSUE TITLE
Google V3: Implement Radius

### ISSUE THREAD

**Issue by adamd** [mapstraction/mxn#11]

**Comment by gilesc50** [comment]
Hi - can you explain what this request is for please?

**Comment by vicchi** [comment]
This issue is 3 years old ... is there/was there a radius function (?) in any other implementations apart from Google V3?

**Comment by gilesc50** [comment]
There is a generic one in mxn.core.js: mxn.Radius and this example uses it: examples/radius.html so closing this issue
