### ISSUE TITLE
AddLayers

### ISSUE THREAD

**Issue by andreszules** [mapstraction/mxn#121]
Hi, I tried this quickly tutorial but it isn't work.

http://blog.slashpoundbang.com/post/1479986159/using-cloudmade-tiles-on-openlayers-maps-with

I dont find AddLayers() funtion in the mapstraction's API documentation. Thanks

**Comment by brunob** [comment]
This seems to be an oopnelayers or cloudmade function, anyway you should use one of mapstraction functions : addOverlay, addTileLayer, etc. This issue should be closed cause it's not a bug.

**Comment by andreszules** [comment]
Thanks ... I close the issue.
