### ISSUE TITLE
swap don't work when try switch to back

### ISSUE THREAD

**Issue by cioxideru** [mapstraction/mxn#124]
for example code from core.html
 `{
                desc: 'Swap API (googlev3)',
                action: function(){
                    m.swap('map', 'googlev3');
                }
            },
            {
                desc: 'Swap API (yandex)',
                action: function(){
                    m.swap('map', 'yahoo');
                }
            },`

**Comment by cioxideru** [comment]
next code fix it problem, I'm not sure that this was intended
at this method 
`Mapstraction.prototype.swap = function(element,api) {`
next line
`if (this.maps[this.api] === undefined || true) {`

**Comment by gilesc50** [comment]
Closing as I don't see any of this code still in the release 3 branch.

**Comment by gilesc50** [comment]
Ah ok I reproduced the issue. create an openlayers map, swap it to Googlev3, then when you swap it back to openlayers again nothing happens.
