### ISSUE TITLE
Tile layer and asset URLs are non-https

### ISSUE THREAD

**Issue by dezfowler** [mapstraction/mxn#141]
Couple of the default tile layer URLs e.g. in the leaflet and openlayers providers are specified with an http rather than https address. This should either be changed to https or made dynamic so it loads from http or https depending on the protocol of the current document location.

**Comment by kersten** [comment]
+1

Will this be implemented?

**Comment by vicchi** [comment]
Yes, it will. We're trying to get through all the pull requests and issues before v3.0 goes out. No timescales as of yet though I'm afraid --- too much day job and too few coders, but that's the way of the world!

**Comment by gilesc50** [comment]
We would also need to get the openlayer default markers via https: http://openlayers.org/dev/img/marker-gold.png - - is this available on https anywhere?

**Comment by gilesc50** [comment]
Also openstreetmap tiles and the mapquest tiles don't appear to be available on https either, so am going to close this unless anyone knows an https source for these?
