### ISSUE TITLE
googlev3 geocode does not work

### ISSUE THREAD

**Issue by ajaysarw** [mapstraction/mxn#145]
HI all, 
when i click on geocode link  it dont reply any thing.
i really dont know what the error i am doing?

-- Ajay --
Here is my code.

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Mapstraction Examples - Google v3</title>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script src="mxn.js?(googlev3,[geocoder])" type="text/javascript"></script>

<style type="text/css">

    #mapdiv {
        height: 400px;
    }

</style> 

<script type="text/javascript">
//<![CDATA[

    var mapstraction;
    var geocoder;

    function geocode_return(geocoded_location) {
        
        // display the map centered on a latitude and longitude (Google zoom levels)
        mapstraction.setCenterAndZoom(geocoded_location.point, 15);

        // create a marker positioned at a lat/lon
        var geocode_marker = new mxn.Marker(geocoded_location.point);

        var address = geocoded_location.locality + ", " + geocoded_location.region;
        geocode_marker.setInfoBubble(address);
        
        // display marker
        mapstraction.addMarker(geocode_marker);

        // open the marker
        geocode_marker.openBubble();
    }

    function initialize() {

        // create mxn object
        mapstraction = new mxn.Mapstraction('mapdiv','googlev3');

        mapstraction.addControls({
            pan: true,
            zoom: 'small',
            map_type: true
        });

        var latlon = new mxn.LatLonPoint(18.47, -69.9);

        mapstraction.setMapType(mxn.Mapstraction.SATELLITE);
        mapstraction.setCenterAndZoom(latlon, 10);
        mapstraction.mousePosition('position');
        
        geocoder = new mxn.Geocoder('googlev3',geocode_return);
        
        // add image overlay
        mapstraction.addImageOverlay("over", "http://mapstraction.com/images/santodomingo.png", 50, -70.01544, 18.39777, -69.80567, 18.563517);

        // add a marker
        var marker = new mxn.Marker(latlon);
        mapstraction.addMarker(marker,true);        
    }
    function user_submit() {
        var address = {};
        address.address = document.getElementById('address').value;
        geocoder.geocode(address);
    }
    
    function changetohybrid(){
        mapstraction.setMapType(mxn.Mapstraction.HYBRID);   
    }   
//]]>
</script> 

</head>
<body onload="initialize();">
    <center>
        <table border='1' width='50%'>
            <tr><td><div id="mapdiv"></div></td>    </tr>
            <tr>
                <td>
                    <input type="text" id="address" name="address" value="" size="35"/>
                    <a href="#" onclick="user_submit(); return false;">Geocode</a>
                </td>
            </tr>
        </table>
        <a href='#' onclick='changetohybrid();'>change to hybrid</a>
        <div id="position"></div>  
    </center>
</body> 
</html>

**Comment by brunob** [comment]
Hi, example updated and working now => #147

**Comment by ajaysarw** [comment]
Thanks,

On Wed, Jun 6, 2012 at 2:59 AM, b_b <
reply@reply.github.com

**Comment by ajaysarw** [comment]
Thanks
