### ISSUE TITLE
OpenLayers: addOverlay for GeoRSS broken

### ISSUE THREAD

**Issue by adamd** [mapstraction/mxn#15]
See http://mapstraction.appspot.com/#georss

**Comment by jpmckinney** [comment]
addOverlay is TODO

**Comment by brunob** [comment]
Hi, addOverlay works for KML but not for GeoRSS. It seems tricky to implement OpenLayers.Layer.GeoRSS has it need to use a proxy to get the content of the feed. So i think we could that addOverlay is done for Openlayers and close this issue.

++

**Comment by vicchi** [comment]
Agreeing with @brunob on this. Flagging as 'wont-fix'
