### ISSUE TITLE
Fix for 'eq' (equal) addFilter

### ISSUE THREAD

**Issue by vignus** [mapstraction/mxn#154]
In the latest mxn.core.js the 'eq' filter is not working. The code snippet is the following:

```
    case 'eq':
        if (o.getAttribute( f[0] ) == f[2]) {
            vis = false;
```

But f[0] must be different from f[2]

So the case 'eq' must be changed in:

```
    case 'eq':
        if (o.getAttribute( f[0] ) != f[2]) {
            vis = false;
```

Hope this help
Mauro

**Comment by gilesc50** [comment]
Thanks, this has been added to the release-3 branch.
