### ISSUE TITLE
Microsoft infobubbles don't work

### ISSUE THREAD

**Issue by russcasey** [mapstraction/mxn#156]
I added this code:
 mapstraction.addMarkerWithData(new mxn.Marker( new mxn.LatLonPoint( 38.8969, -77.070857 )),{
          infoBubble : "Advanced Marker",
          label : "tooltip",
           date : "new Date()",
          marker : 4,
                iconShadow: "http://mapstraction.appspot.com/images/blank.png",
         iconShadowSize : [0,0],
          icon : "http://mapstraction.appspot.com/images/usgs_marker.png",
          iconSize : [20,20],
          draggable : false,
          hover : true
      });

..into the initialize function here: http://mapstraction.appspot.com/#switching_providers

It works beautifully for every type of map except MS. :(

**Comment by gilesc50** [comment]
They do seem to work in the core tests for microsoft6, so this looks like it can be closed.

**Comment by vicchi** [comment]
Agreed. InfoBubbles are working with both the `microsoft6` and `microsoft7` providers; closing this issue.
