### ISSUE TITLE
mapscratcion.swap(api, element)

### ISSUE THREAD

**Issue by Gectou4** [mapstraction/mxn#158]
Hi there 

Followed to http://mapstraction.com/mxn/build/latest/docs/symbols/mxn.Mapstraction.html#swap docs
the swap funciton should be designed as followed :
swap(api, element)

But on it's mxm.core.js designed as followed:
/**
- Change the current api on the fly
- @param {String} api The API to swap to
- @param element
  */
  Mapstraction.prototype.swap = function(element,api) {

that's not a big deal, but can confuse someone :)

regards,

**Comment by dezfowler** [comment]
Thanks for pointing this out - fixed with commit 762897a30e
