### ISSUE TITLE
Fix build script to use correct min arguments.

### ISSUE THREAD

**Issue by vicchi** [mapstraction/mxn#164]
The build currently complains of ...

`[java] The args attribute is deprecated. Please use nested arg elements`

... when minimising the built source files. This should be fixed to use the new form of min command line args.

**Comment by dezfowler** [comment]
I could have sworn someone had fixed this already.

Maybe its buried in one of the outstanding pull request or there was a
conflicting change and it was lost.

Derek

**Comment by vicchi** [comment]
Possibly, there's still 7 for me to plough through. But if it's not buried in a pull request, I'll fix it up. This issue was more an aide memoire for me rather than anything else.

**Comment by vicchi** [comment]
Fixed on `integration` branch; see commit 8939b14538c9410f5065016e765cf7c017641834
