### ISSUE TITLE
Fix for BoundingBox contains across date line

### ISSUE THREAD

**Issue by FollowMySpot** [mapstraction/mxn#174]
The function `BoundingBox.prototype.contains` in mxn.core.js does not work if the western longitude  is greater then the eastern longitude (across the dateline - particularly relevant for New Zealand)
The code:

```
BoundingBox.prototype.contains = function(point){
    return point.lat >= this.sw.lat && point.lat <= this.ne.lat && point.lon >= this.sw.lon && point.lon <= this.ne.lon;
};
```

should be:

```
BoundingBox.prototype.contains = function(point){
    return point.lat >= this.sw.lat && point.lat <= this.ne.lat
        && ((this.sw.lon <= this.ne.lon && point.lon >= this.sw.lon && point.lon <= this.ne.lon)
            || (this.sw.lon > this.ne.lon && (point.lon >= this.sw.lon || point.lon <= this.ne.lon)));
};
```

**Comment by vicchi** [comment]
Nice catch. Thanks for spotting this and for giving a fix as well. I'll make sure this gets into the next release.

**Comment by FollowMySpot** [comment]
Thanks Gary, this is a great project and I would like to support and  
contribute to it as much as I can. I really appreciate all the time you  
and others are putting into this. I have some other changes I will add  
too, mostly for microsoft7. I'm also currently working on updating the  
googleearth api which is a little tricky as it works quite differently to  
other providers, unfortunately it will take some time and will not be  
ready for the next release

**Comment by vicchi** [comment]
Keep the fixes and changes coming! Either as issues or feel free to fork yourself a copy and do the whole pull request thing.

**Comment by FollowMySpot** [comment]
Will do, I'm a GitHub virgin so I'm just taking baby steps at the moment!  
I'll try the fork to see how that goes as I can see there is a lot to do  
on the microsoft7 and googleearth providers and a fork may be easier

**Comment by vicchi** [comment]
Go. Do it. The great thing about GitHub is that you can't really do anything catastrophic and even if you do you can just pull your changes back from your forked repository.

**Comment by vicchi** [comment]
Fixed on the `integration` branch; see commit 34f94d9a2cea8152a8ed3934b6ea2bd04d2b5252
