### ISSUE TITLE
Tile URL for googlev3.core

### ISSUE THREAD

**Issue by FollowMySpot** [mapstraction/mxn#176]
Currently the tile url only works in the main central portion of the map. The co-ordinate google uses continues increasing to the right and reduces (negative numbers to the left of the date line. For example at zoom level 6 the x co-ordinate ranges from 0 to 63 for the main central portion of the map but increases to 64, 65 etc. to the right. To only store the map tiles once the getTileUrl function of addTileLayer needs to be changed from:

``` javascript
    getTileUrl: function (coord, zoom) {
        url = tile_url;
        url = url.replace(/\{Z\}/g, zoom);
        url = url.replace(/\{X\}/g, coord.x);
        url = url.replace(/\{Y\}/g, coord.y);
        return url;
    },
```

to:

``` javascript
    getTileUrl: function (coord, zoom) {
        url = tile_url;
        var x = coord.x;
        var maxX = Math.pow(2, zoom);
        while (x < 0)
            x += maxX;
        while (x >= maxX)
            x -= maxX;
        url = url.replace(/\{Z\}/g, zoom);
        url = url.replace(/\{X\}/g, x);
        url = url.replace(/\{Y\}/g, coord.y);
        return url;
    },
```

**Comment by vicchi** [comment]
Implemented on the `integration` branch; see commit 2753b0da0f4fa83f2161cdcf26befc2e49443ccd
