### ISSUE TITLE
openlayers setMapType function

### ISSUE THREAD

**Issue by FollowMySpot** [mapstraction/mxn#180]
The setMapType function in mxn.openlayers.core throws an exception, this should be removed or maybe replaced with console.log. setMapType is called by the mxn.core swap function to switch between different providers - it is still valid to call it, just don't do anything

**Comment by vicchi** [comment]
Agreed. For providers which don't support differing map types, `setMapType()` should effectively devolve to a no-op. Personally I don't think logging via `console.log()` should be used for anything other than debugging during development but I agree that throwing an exception is definitely not the way we should handle this.

**Comment by vicchi** [comment]
Fixed as part of Pull Request #173; see commit 630d41b80dac65a72a650833a3e9fd255fccc399
