### ISSUE TITLE
Nokia map types

### ISSUE THREAD

**Issue by FollowMySpot** [mapstraction/mxn#181]
The nokia setMapType function throws an exception when the type is `mxn.Mapstraction.HYBRID`, for mxn.core swap function to work correctly both `mxn.Mapstraction.HYBRID` and `mxn.Mapstraction.SATELLITE` should both set the base map type to `map.SATELLITE` as in:

``` javascript
    setMapType: function(type) {
        var map = this.maps[this.api];

        switch (type) {
            case mxn.Mapstraction.ROAD:
                map.set("baseMapType", map.NORMAL);
                break;
            case mxn.Mapstraction.PHYSICAL:
                map.set("baseMapType", map.TERRAIN);
                break;
            case mxn.Mapstraction.HYBRID:
            case mxn.Mapstraction.SATELLITE:
                map.set("baseMapType", map.SATELLITE);
                break;
            default:
                map.set("baseMapType", map.NORMAL);
                break;
        }   // end-switch ()
    },
```

In fact I would go one step further, as from a purely abstract implementation you would say that Nokia's `map.SATELLITE` map type is equivalent to Mapstraction's `mxn.Mapstraction.HYBRID`. Again, the swap function would work better if getMapType() returned `mxn.Mapstraction.HYBRID` instead of `mxn.Mapstraction.SATELLITE` - this way if you switch back and forward between Google's hybrid view and Nokia's 'Satellite' view you see labels for both. This would make the getMapType function:

``` javascript
    getMapType: function() {
        var map = this.maps[this.api];
        var type = map.baseMapType;

        switch (type) {
            case map.NORMAL:
                return mxn.Mapstraction.ROAD;
            case map.TERRAIN:
                return mxn.Mapstraction.PHYSICAL;
            case map.SATELLITE:
                return mxn.Mapstraction.HYBRID;
            default:
                return null;
        }   // end-switch ()
    },
```

There are good arguments for and against this, if you're using Nokia stand-alone 'Satellite' makes more sense as a descriptor since Nokia does not have both 'Satellite' and 'Hybrid' map types. I'm happy either way though I prefer 'Hybrid' for my own implementation.

**Comment by vicchi** [comment]
Which branch are you looking at? The `setMapType()` and `getMapType()` methods were updated in commit 8a6958f9825175603d319e8ef9ff6ebfca28ba38 on the `integration` branch on November 15th ...

`

**Comment by vicchi** [comment]
MXN.Mapstraction.ROAD == nokia.maps.map.Display.NORMAL
MXN.Mapstraction.PHYSICAL == nokia.maps.map.Display.TERRAIN
MXN.Mapstraction.HYBRID == nokia.maps.map.Display.SATELLITE
MXN.Mapstraction.SATELLITE == nokia.maps.map.Display.SATELLITE_PLAIN

**Comment by FollowMySpot** [comment]
You're right, I am using an old implementation, I'll close this off. BTW,  
very nice job on this Gary, it all seems to work very well.

**Comment by vicchi** [comment]
Cool. No problem. Thanks for letting me know.
