### ISSUE TITLE
MXN: Do not display alerts to the end user

### ISSUE THREAD

**Issue by adamd** [mapstraction/mxn#20]
Mapstraction methods should raise known exceptions and be documented to 
allow the client code to catch and display suitable application messages 
to the user.

**Comment by vicchi** [comment]
Wholeheartedly agree. The next release of Mapstraction will no longer display an alert when the provider API hasn't been included, as in ...

``` javascript
alert (api + ' map script not imported');
```

... but will throw a generic JavaScript `Error` exception, as in ...

``` javascript
throw new Error (api + ' map script not imported');
```

**Comment by vicchi** [comment]
Resolved on the `integration` branch; see commit a3e14af0ac31fdc14162ac7cdbc89b59eddafdd3
