### ISSUE TITLE
Microsoft infobubbles still don't work

### ISSUE THREAD

**Issue by david-mansion** [mapstraction/mxn#206]

**Comment by vicchi** [comment]
What's not working with them? I've just run the core tests on both the `microsoft` (Bing v6) and `microsoft7` (Bing v7) providers and InfoBubbles are working fine.

What version of Mapstraction are you testing against? Can you provide a code sample that shows this?

**Comment by david-mansion** [comment]
http://www.ilyatoo.com/produitsimple.php?info_typeoeuvre=Carte%20Géographique
look at TEST MAPSTRACTION BING item (bottom of page)

**Comment by vicchi** [comment]
Sorry ... that page doesn't load at all. As I've already asked .. what version of Mapstraction are you using and can you provide the code that shows this issue?

**Comment by vicchi** [comment]
InfoBubbles for both the `microsoft` and `microsoft7` providers seems to be working. Closing this issue.
