### ISSUE TITLE
Are line and polygon expected ?

### ISSUE THREAD

**Issue by david-mansion** [mapstraction/mxn#207]
is it possible to do somthing like this : http://services.articque.com/projets/exemplescdweb/bing_google/

**Comment by vicchi** [comment]
Not quite sure what the question is ... Mapstraction supports polygons and polylines. What is it you're trying to do?

**Comment by david-mansion** [comment]
i try to do the same as http://services.articque.com/projets/exemplescdweb/bing_google/
put layer with surface colored with transparency

**Comment by vicchi** [comment]
You can certainly add multiple polygons with alpha (transparent fill) and some (but currently not all) supported maps providers allow image overlays.

**Comment by david-mansion** [comment]
cool, so where can i find code exemples for these polygons ?
another questions : 
is there any website list using Mapstraction ?
is it better to copy .js file on my server ?
thanks to reply so fast

**Comment by vicchi** [comment]
> cool, so where can i find code exemples for these polygons ?

For now, the best place to find code samples are in the `examples` directory on the v2.1 release branch; see https://github.com/mapstraction/mxn/tree/release-2.1/examples.

> is there any website list using Mapstraction ?

Not that I know of; this is always a challenge when running a free open source project which doesn't require any registration or authentication.

> is it better to copy .js file on my server ?

For now, yes. I strongly recommend forking the project and using the `release-2.1` branch. Once this version gets released you should be able to link via the mapstraction.com domain.

**Comment by vicchi** [comment]
No response to this issue for over a month; closing as part of the issues cleanup.
