### ISSUE TITLE
api google map V3 vs V2

### ISSUE THREAD

**Issue by david-mansion** [mapstraction/mxn#208]
because of the change in google api/key, in your code, i replace this :

<script type="text/javascript" src="http://maps.google.com/maps?file=api&v=2&key=ABQIAAAATndsWAV5Q2y7pRRi-22W_hQyCh59sTxL7LKA0f7jwSjVtdSeYBSa-_7XV0fjT8X9AzrGynqNsiXWjQ&sensor=false"></script>

by this :

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

but it doesn't work. 
i can't have a key with the new google api account...

**Comment by vicchi** [comment]
Your post got mangled and seems to be missing some sections ... can you repost?

**Comment by david-mansion** [comment]
because of the change in google api/key, in your code, i replace this :
   script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAYfI_xw3MwUbmAScWsa72VBRlOb26qSyU154aZeLwOrF4C7-DphRd2PMapEng5PbZ2SmtYsveejDHpw"></script

by this
script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script

but it doesn't work.
i can't have a key with the new google api account...

**Comment by vicchi** [comment]
What doesn't work? You're right that v3 of the Google Maps API doesn't require a key. But as I asked on one of your previous posts ... what version of Mapstraction are you using? Can you provide a code sample that shows your problem? And what, precisely, doesn't work?

**Comment by david-mansion** [comment]
i took 3 examples of your sandbox :
http://www.clicage.com/mapstraction_bing.html
http://www.clicage.com/mapstraction_google_map.html
http://www.clicage.com/mapstraction_yahoo.html

**Comment by vicchi** [comment]
The sandbox is fairly old and hasn't been updated for a while; indeed it probably won't get updated until v2.1 of Mapstraction is released. Until then, please use the examples in the `release-2.1` branch at https://github.com/mapstraction/mxn/tree/release-2.1/examples

**Comment by david-mansion** [comment]
ok great, here are my test :

Google :
http://www.clicage.com/mapstraction/googlev3-basic.html
infobuble : Ok
polygon : black (no alpha)

Bing :
http://www.clicage.com/mapstraction/microsoft-basic.html
infobublle : KO (no text, even on mousemove)
polygon : OK

**Comment by vicchi** [comment]
... thanks ... and I can see you're hosting Mapstraction locally ... which version are you using? The `release-2.1` branch or the `master` branch?

**Comment by david-mansion** [comment]
i suppose it's master because i used 
https://github.com/mapstraction/mxn

then

https://github.com/mapstraction/mxn/tree/master/source
then copy and paste sources (can't download) :
mxn.core.js
mxn.googlev3.core.js
mxn.js
mxn.microsoft.core.js

then 

https://github.com/mapstraction/mxn/tree/master/examples
googlev3-basic.html
microsoft-basic.html

I DON'T REMEMBER WHERE I FOUND :
examples.css

is it good ?

how about 2 bugs :
bing - infobublle : KO (no text, even on mousemove)
google - polygon : black (no alpha)

**Comment by vicchi** [comment]
You're right; the `master` branch is the (old) version, which is v2.0.18, released in March 2012 (https://github.com/mapstraction/mxn/wiki/Changelog).

You can always find the official release versions for download at https://github.com/mapstraction/mxn/downloads but you should really be testing/using the latest release candidate for v2.1 which is RC2 and you can find a download for that here: https://github.com/mapstraction/mxn/tags.

Try again with the latest version and if you continue to have problems, please share your example code, but not copy and pasted into this thread, but as a Gist.

**Comment by vicchi** [comment]
No response to this issue for over a month; closing as part of the issues cleanup.
