### ISSUE TITLE
Oplenlayers polyline show/hide

### ISSUE THREAD

**Issue by FollowMySpot** [mapstraction/mxn#209]
The openlayers Polyline hide/show functions do not work, they need to have the layer redrawn after the style display is set:

``` javascript
        show: function() {
            this.proprietary_polyline.style.display = "block";
            this.proprietary_polyline.layer.redraw();
        },

        hide: function() {
            this.proprietary_polyline.style.display = "none";
            this.proprietary_polyline.layer.redraw();
        }
```

**Comment by vicchi** [comment]
Nice catch. Thanks for this. I did actually think that this wasn't an issue, at least initially, as the core tests seemed to work but when I looked at the test code, it exercises the creation/deletion of a `Polyline` and (crucially) not the `show` or `hide` methods. So you're spot on.

I'll get this into the `release-2.1` branch this morning.

Thanks again.

**Comment by vicchi** [comment]
Fixed/implemented on the `release-2.1` branch; see commit 9ba98c707469e6815ecbf40276fa3a70f75089c2

**Comment by dezfowler** [comment]
Just had a look at this, think it should probably be calling the OpenLayers setVisibility function instead:
http://dev.openlayers.org/apidocs/files/OpenLayers/Layer-js.html#OpenLayers.Layer.setVisibility

**Comment by vicchi** [comment]
@dezfowler - I think you're right. `OpenLayers.Layer.setVisibility` is pretty much doing what `mxn.openlayers.core.js` is doing, at least in principle, but it's doing more into the bargain. I'll make this change.

**Comment by vicchi** [comment]
Reworked and committed to the `release-2.1` branch; see commit 823ea15e519cfae1559bb8ffec64d9c971b4cb42
