### ISSUE TITLE
MXN: Webkit browser auto-loading issues

### ISSUE THREAD

**Issue by adamd** [mapstraction/mxn#21]
For now a workaround is to comment out the first function in mxn.js which loads all of the libraries we need and to load them manually in the html.

aka. instead of:

<script src="mxn.js?(google)" type="text/javascript"></script>

do:

<script src="mxn.js" type="text/javascript"></script>

<script src="mxn.core.js" type="text/javascript"></script>

<script src="/mxn.google.core.js" type="text/javascript"></script>

**Comment by vicchi** [comment]
Err? Not too sure what this means. Care to clarify? Looks like something got munged when this issue was originally logged.

**Comment by vicchi** [comment]
3 years on and I've still no real clue about this issue. Closing it down.
