### ISSUE TITLE
latitude-longitude vs longitude-latitude

### ISSUE THREAD

**Issue by david-mansion** [mapstraction/mxn#210]
why mapstraction ask longitude-latitude as kml file are latitude-longitude ?
is ther any possibility ok swap these cols ?

**Comment by vicchi** [comment]
Not sure I understand ... are you talking about the order of parameters to a `LatLonPoint` ... ?

**Comment by david-mansion** [comment]
yes,
mapspstraction parameter are LatLong order :
polyline = new mxn.Polyline([
new mxn.LatLonPoint(47.42968024, 1.08501332),
new mxn.LatLonPoint(47.4086325, 1.1105271),

in a kml ascii file, it"s inverse : Lon Lat
<coordinates>  
1.08501332,47.42968024,0 1.1105271,47.4086325,0 1.11339735,47.39847023,0.....
</coordinates>
It should be easer to create a javascript source file with the coordinate kml just with a search/replace 'space' by 'new mxn.LatLonPoint('...

**Comment by vicchi** [comment]
OK. I understand you now. But KML is the odd one out in specifying coordinates in long/lat order. Mapstraction and every single one of the maps providers that it supports all specify coordinates in lat/long order when specifying a point.

I can't support changing the constructor for `LatLonPoint` as this would effectively break compatibility with every single user of Mapstraction and that's not something I'd ever want to do unless there's a really good reason and to change this based on a single data format isn't a good enough reason I'm afraid.

You'll just need to do a little text processing to extract KML format coordinates and swap the coordinate order; you'd have to do this regardless of whether you're using Mapstraction or one of the other mapping APIs directly.

**Comment by ajturner** [comment]
Well, Lat,Lon order is the outlier actually as that is Y,X instead of the more standard X,Y. 

GeoJSON is Lon,Lat (except twitter messed theirs up and reversed it to Lat,Lon)

An unfortunate situation of English language and alphanumeric sorting.

But I agree that we shouldn't break API compatibility and atleast the method name indicates order.

**Comment by vicchi** [comment]
This is a semantically odd one ...
- Most mapping APIs use Y,X (lat/lon)
- Most (spatial) data formats use X,Y (lon/lat)
- Other APIs, which have a spatial component, use whichever format they seem to like

... there are exceptions to the above of course.

But you're right, we need to maintain the API contract and all the back-end mapping providers also use lat/lon order in their point constructors, with the exception of those APIs which don't have a constructor for their point representation and just allow you to write directory to either the class members or just use an array.

**Comment by david-mansion** [comment]
I don't know how you develop mapstraction, but is it hard to add a fonction LonLatPoint and keep LatLonPoint ?
of course it's my job to manipulate data so no problemo to extract kml in cols and swa them...
another question : is it better to store polygon datas in ascii file or in sql database ? what mapstraction user choose ?

**Comment by vicchi** [comment]
You could easily create a `LonLatPoint` but the problem with that is that every other function in Mapstraction that takes a point as an argument expects a `LatLonPoint` so you'd have to effectively duplicate a large amount of the Mapstraction code base. You can't even overload `LatLonPoint` as Javascript doesn't supported overloaded function names and even if it did, it only uses the number of arguments as function signatures so `LatLonPoint(lat, lon)` would be seen as identical to `LatLonPoint(lon,lat)`.

> is it better to store polygon datas in ascii file or in sql database ?

It depends on what you want to do with them. GeoCouch is a good place to store text based files, MySQL is a good general purpose database and PostgreSQL with PostGIS is a good choice if you want to do spatial queries with your data.

**Comment by david-mansion** [comment]
thanks RC2 is OK
http://www.clicage.com/mapstraction2_1RC2/microsoft-basic.html (steal no infobubble, i'll seek)
http://www.clicage.com/mapstraction2_1RC2/googlev3-basic.html

be carefull a mistake in
googlev3-basic.html
and
microsoft-basic.html
(the only 2 i use) :
<body></body>
<div id="map"></div>    </div></html>

**Comment by vicchi** [comment]
Err ... the `-basic.html` examples don't have any code in them to create a `Marker` or an `InfoBubble`.

`examples/googlev3.html` works fine with an `InfoBubble` , at least on my local installation, but there does seem to be a problem with `examples/microsoft.html` ... I'll take a look at this

**Comment by david-mansion** [comment]
perhaps another problem with marker1.setShadowIcon
OK on http://www.clicage.com/mapstraction2_1RC2/googlev3-basic.html
KO on http://www.clicage.com/mapstraction2_1RC2/microsoft-basic.html
(with the same code)

**Comment by dezfowler** [comment]
It's pretty straight forward to parse the KML into points or polygons or
whatever is most appropriate and I imagine most examples of doing this for
the other providers would work similarly for Mapstraction.

Making an API change because of a minor inconvenience with KML would result
in a major inconvenience for most Mapstraction users.

Derek

**Comment by vicchi** [comment]
> perhaps another problem with marker1.setShadowIcon
> OK on http://www.clicage.com/mapstraction2_1RC2/googlev3-basic.html
> KO on http://www.clicage.com/mapstraction2_1RC2/microsoft-basic.html
> (with the same code)

This is expected behaviour; versions 6.3 and 7.0 of the Microsoft Bing maps APIs do not support or implement custom icon shadows for a marker/pushpin, so I wouldn't expect this to work in Mapstraction.

You can find a full list of what is and isn't supported on the wiki at https://github.com/mapstraction/mxn/wiki/Supported-Map-API-Providers (although I do need to update this to include shadow icons for markers)
