### ISSUE TITLE
Nokia marker click event

### ISSUE THREAD

**Issue by FollowMySpot** [mapstraction/mxn#214]
The Nokia provider does not have the click event assigned to a marker. At the end of the Marker toProprietry() function the following should be added just before the return statement

``` javascript
        prop_marker.addListener('click', function (event) {
            prop_marker.mapstraction_marker.click.fire();
        }, false);
```

**Comment by vicchi** [comment]
Added for both Nokia and Ovi providers; see commit 8a3e972a9089323ead482993723e65adf6f353db
