### ISSUE TITLE
Cloudmade mousePosition bug

### ISSUE THREAD

**Issue by FollowMySpot** [mapstraction/mxn#215]
There is an error in the mousePosition function for couldmade, the line:

``` javascript
var loc = point.latLng.lat().toFixed(4) + ' / ' + point.latLng.lng().toFixed(4);
```

should read:

``` javascript
var loc = point.lat().toFixed(4) + ' / ' + point.lng().toFixed(4);
```

**Comment by vicchi** [comment]
This seems to have already been fixed in commit f9646094cf53b1df5c97af40c022bc0be5c2e7a6 by @gilesc50, albeit in a slightly different manner.
