### ISSUE TITLE
Serving mxn.js from 'raw.github.com' causes it to fail executing on Chrome Canary (27.0.1429.0)

### ISSUE THREAD

**Issue by lxe** [mapstraction/mxn#219]
The tutorial at http://mapstraction.com/tutorial/ currently states that you should include "https://raw.github.com/mapstraction/mxn/master/source/mxn.js?(openlayers)" script.

However, Chrome Dev and Canary builds, seem to prevent scripts served with improper MIME type from running.

I've contacted GitHub and failed a chromium bug here: https://code.google.com/p/chromium/issues/detail?id=180007

I think the tutorial needs to be adjusted to say that the files need to be hosted outside GitHub, if running on Chrome, once the dev/canary version becomes stable.

**Comment by dezfowler** [comment]
Thanks for this information Aleksey.

I've never been a fan of the Github hosting option, always seemed risky to
me, especially since Github can and do remove features.

If there is great demand for a CDN hosted version of some kind we probably
need to look at whether there is a good free option open to us.

Derek

**Comment by vicchi** [comment]
This is well spotted. On the one hand, you could argue that users of the Chrome Development and Canary builds are in a minority. But on the other hand, and more importantly, this does highlight the issue of how and where we host releases of Mapstraction.

> However, Chrome Dev and Canary builds, seem to prevent scripts served with improper MIME type from running.

It actually looks as if GitHub are doing the _right thing_ and serving up the files with the `X-Content-Type-Options: nosniff` header to deter people from using GitHub's `raw` mode as a CDN. There's a comment in the Chrome bug thread you opened which really made me sit up and take notice of this ...

> I've had conversations with GitHub folks about this issue in particular; they don't actually want folks serving files
> from raw.github.org, which is why they serve resources with the 'nosniff' header. They'd prefer that you set up
> something on GitHub Pages.

So what I propose is the following ...

For now, I update the documentation and the mapstraction.com site as a whole to a) say download the code and host it locally and b) not to link to GitHub.

> If there is great demand for a CDN hosted version of some kind we probably need to look at whether there is a good free option open to us.

Once v2.1 of the code (which will actually be v3.0 but that's another subject entirely) ships (which means when I get the time to finish it off), we submit Mapstraction for CDN hosting with [cdnjs](http://cdnjs.com/) which is free for open source Javascript projects and Mapstraction seems to fit the eligibility criteria (in excess of 100 watchers on GitHub).

Thoughts?

-Gary

**Comment by dezfowler** [comment]
Sounds good to me, will take a look at cdnjs and see whether we could hook
something up to TeamCity.

Derek Fowler

(comment edited to remove email thread)

**Comment by vicchi** [comment]
So this feature has now made it from Chrome Canary into Chrome proper. I've updated the mapstraction.com homepage and tutorials to make it clear that you shouldn't pull MXN from `raw.github.com` and also to point people to the right way of doing things. See http://mapstraction.com/tutorial/.

We still need to do the whole cjdns thing once MXN v3.0 goes out the door.
