### ISSUE TITLE
Google V3: Add Map Type support

### ISSUE THREAD

**Issue by adamd** [mapstraction/mxn#23]

**Comment by brunob** [comment]
Not completly shure but this one seems to be fixed now.

**Comment by brunob** [comment]
I think this issue should be close, no ?

**Comment by vicchi** [comment]
This is ambiguous. Could either refer to the `addMapTypeControls()` core API call, or `setMapType()` and/or `getMapType()`. I really should look at the git history but either way, all of the above are implemented so closing as 'wont-fix'.
