### ISSUE TITLE
Create a subfolder of examples that always pull the latest version of the api’s

### ISSUE THREAD

**Issue by gilesc50** [mapstraction/mxn#232]
we should have a subfolder of examples that always pull the latest version of the api’s as well? (making it easier for us to check after new versions are released?)

result of discussions on whether to upgrade openlayers references to always pull the latest.

**Comment by vicchi** [comment]
I've just taken a look at this and have to ask whether this is actually worth it? Mapstraction supports 14 different maps providers, soon to be 13 when the Google v2 API goes away.

Of these 14, ArcGIS, MapQuest and MapQuest Open, Microsoft, Nokia HERE and Ovi and Yandex all require an explicit version number, there's no _latest_ shortcut URL.

CloudMade, Leaflet and OpenLayers provide a _latest_ shortcut and OpenSpace doesn't provide _anything_ but a latest version.

Google provides some versioning, but only to the major release number.

So we could really only implement this for 3 providers; CloudMade, Leaflet and OpenLayer, actually 4 if you include OpenSpace. That's 10 provider we can't test for in this way.

Is this worth the time and effort for 4 providers? I'm not so sure.

**Comment by gilesc50** [comment]
Agreed, closing the issue.
