### ISSUE TITLE
setBounds failure and fix

### ISSUE THREAD

**Issue by djeeg** [mapstraction/mxn#242]
Within mxn.microsoft7.core.js

Function SetBounds, this line:
    var viewRect = Microsoft.Maps.LocationRect.fromCorners(new Microsoft.Maps.Location(sw.lat,ne.lon), new Microsoft.Maps.Location(ne.at,sw.lon));

Is missing a L on the last parameter
Should be
    var viewRect = Microsoft.Maps.LocationRect.fromCorners(new Microsoft.Maps.Location(sw.lat,ne.lon), new Microsoft.Maps.Location(ne.lat,sw.lon));

**Comment by djeeg** [comment]
Actually now i believe that the points order needs to be swapped too

To be:

var viewRect = Microsoft.Maps.LocationRect.fromCorners(new Microsoft.Maps.Location(ne.lat,sw.lon), new Microsoft.Maps.Location(sw.lat,ne.lon));

**Comment by vicchi** [comment]
Nice. I'll take a look. Thanks

**Comment by gilesc50** [comment]
Looks like this has been fixed and is working ok now in release 3
