### ISSUE TITLE
setInfoBubble windows 7 problem

### ISSUE THREAD

**Issue by vicoludo** [mapstraction/mxn#243]
Hi,
I've cretaed a map with Microsoft 7, and a series of markers, and everything is fine. I tired to add a bubble marker, and by doing that it doesn't display it on the map any more. This is the code:

```
              var microsoft_key = "####";

            mapstraction = new mxn.Mapstraction('mapdiv','microsoft7');

        var latlon = new mxn.LatLonPoint(55.37911,-3.427734);

        mapstraction.setMapType(mxn.Mapstraction.ROAD);
        mapstraction.setCenterAndZoom(latlon, 5);

        mapstraction.addControls({
            pan: true,
            zoom: 'small',
            map_type: true
        });

     var mk = new mxn.Marker(new mxn.LatLonPoint(point.latitude, point.longitude));
    mk.setInfoBubble('test');
    mapstraction.addMarker(mk);
    mk.openBubble();
```

Firebug shows this error:
ReferenceError: map is not defined
Microsoft.Maps.Events.addHandler(map, 'viewchange', function () {
mxn.microsoft7.core.js (riga 376)

**Comment by vicchi** [comment]
What version of Mapstraction are you using for this?

-Gary

**Comment by vicoludo** [comment]
v2.0.18

**Comment by vicchi** [comment]
Can you try again, but this time use the v2.1 release candidate instead (https://raw.github.com/mapstraction/mxn/release-2.1/source/mxn.js) and see if this recurs?

-Gary

**Comment by vicoludo** [comment]
No, sorry, I still get the same error

**Comment by vicchi** [comment]
OK. Can you share the whole of your working example please? Preferably as a Gist. I'll take a look and see what's going on. 

-Gary

**Comment by vicchi** [comment]
See this gist - https://gist.github.com/vicchi/5476881 - this is working for me. Wondering if the problem is down to point not being defined in your code (although it may be elsewhere and just not shown in your sample code).

-Gary

**Comment by vicoludo** [comment]
Hi,
I've used the code you sent, it displays the marker on the map, but it doesn't open the bubble, and the error i get is the following:
TypeError: Microsoft.Maps.InfoBox is not a constructor
description: this.infoBubble

**Comment by vicchi** [comment]
I can't reproduce this. What line number is the error you're seeing being reported at?

**Comment by vicoludo** [comment]
I've found that if I download the  2.1 release onto my server and I use it locally, I get an error if i call it from https://raw.github.com/mapstraction/mxn/release-2.1/source/mxn.js?(microsoft7) it works

**Comment by vicchi** [comment]
Very odd. Take a look at http://maps.geotastic.org/test.html ... this is publicly accessible and is a working version of the gist I posted earlier. Can you confirm it works for you?

**Comment by vicoludo** [comment]
Yes, your example works.

**Comment by vicchi** [comment]
Phew. That's a relief. If you do a 'view-source' and compare ... is there a difference between my example and your code? Trying to pin down whether this is an environment issue or a code issue.

**Comment by vicoludo** [comment]
Hi, regarding the maps from yesterday. Everything now works however I've added setHover
  var map;
  var microsoft_key = "xxxxx";
  function initialize() {
  map = new mxn.Mapstraction('map', 'microsoft7');
  var latlon = new mxn.LatLonPoint(55.37911,-3.427734);
  map.setMapType(mxn.Mapstraction.ROAD);
  map.setCenterAndZoom(latlon, 5);

  var mk = new mxn.Marker(latlon);
  mk.setInfoBubble('test');
  map.addMarker(mk);
  //mk.openBubble();
  mk.setHover(true);
 }
  $(document).ready(function() {
  initialize();
 });
But it doesn't work, and I'm not getting any errors…

Thanks in advance,

**Comment by vicchi** [comment]
From looking at the Microsoft/Bing v7 implementation, it seems like `hover` support for `mxn.Marker` isn't implemented. This needs to be fixed. I'll try and get around to this this week.

**Comment by vicoludo** [comment]
Hi, 

A few weeks back we chatted about the Microsoft/Bing v7 implementation  hover support for mxn.Marker 
You said you'd get round to fixing it in the coming days, did you have any luck?

Regards,

**Comment by gilesc50** [comment]
This should now be working for you in release-2.1
