### ISSUE TITLE
Google Maps v3 visual refresh (the «new» Google Maps).

### ISSUE THREAD

**Issue by ChALkeR** [mapstraction/mxn#249]
Google is now testing new Google Maps: http://maps.google.com/preview
It includes refreshed tiles and controls.

The API v3 was also updated:
https://developers.google.com/maps/documentation/javascript/basics#VisualRefresh

> The Google Maps visual refresh brings a fresh new look to applications using the Google Maps JavaScript API. The refresh is a seamless upgrade that aligns the Google Maps API user experience with the new Google Maps.

This is an opt-in for now (version 3.12), via global property `google.maps.visualRefresh`, but in November (release 3.14) it will be turned on by default:

> The new look is available as an opt-in upgrade today, and will become the default style in our experimental branch with the next scheduled release in August. Three months later, in our November release, the visual refresh will become the default style in our release branch (used by most Maps for Business customers).

Version 3.11 (Frozen) has no `visualRefresh` support, as it seems.

The changes are mostly visual, but there are some API changes as well:
https://developers.google.com/maps/documentation/javascript/basics#VisualRefreshChanges

In particular:

> The marker property raiseOnDrag has been replaced by crossOnDrag.

Seems to be not used by mxn.

> All shadows have been removed in the visual refresh. Any shadows specified programmatically will be ignored.

The only shadows that are used in mxn are marker icon shadow images. The visual refresh makes that option ignored: https://developers.google.com/maps/documentation/javascript/3.exp/reference#MarkerOptions

It looks like nothing should be done. As it seems, specifing ignored shadows would not produce an error and everything would work just fine when the visual refresh will be turned on by default. Maybe setting marker shadows (unused in the new API) should get removed, but actually they do no harm, and what if someone uses frozen googlev3 api (3.11), which has marker shadows support?

But just in case, it should be checked how well does googlev3.core work (and look) with `google.maps.visualRefresh` enabled.

**Comment by gilesc50** [comment]
Good analysis, thanks and I agree that nothing needs to be done.
I ran the core tests and one of my own projects with `google.maps.visualRefresh = true;` and all seemed well.
