### ISSUE TITLE
Check MapStraction Version

### ISSUE THREAD

**Issue by icebergdelphi** [mapstraction/mxn#250]
HI all, does exist a way to check mapstraction version? because i was testing some versions, with my app, but  some versions of Mapstraction give me errors and not others.  Thanks.

**Comment by vicchi** [comment]
At the moment, no. But there will be in the next release.

-Gary

**Comment by vicchi** [comment]
Implemented as `mxn.Version` (version number in major.minor format) and `mxn.Build` (build number in major.minor.build format) literals, for v3.0 of the code base,  automagically updated by the ant build script. See commit ca3f559be2e1a2adcdd79a9466f3064e7b77e508
