### ISSUE TITLE
How to get Polyline or Polygone data to use it in a Geofence?

### ISSUE THREAD

**Issue by icebergdelphi** [mapstraction/mxn#252]
Hi all, does exist an example how to create a Geofence? or how i get the data from Polyline and Polygon?
Thanks to all.

**Comment by icebergdelphi** [comment]
Ok i have some advances how to create a Polygon, but is there a doubleclick event?

i draw a Polygon but with click event i need to doit with doubleclick:
//Dibujar Geofence////////////
         DrawGeofence=function(){
            var points = [];
            //Show Clicked Points
             mapstraction.click.addHandler(function(eventName, eventSource, eventArgs) {
             var coords = eventArgs.location;   // coords are an mxn.LatLonPoint object
             points.push(coords);
             var polygon = new mxn.Polyline(points);
             polygon.setColor('#F00014');
             polygon.setWidth(3);
             polygon.setClosed(true);
             mapstraction.addPolyline(polygon)

```
        }); 

     }
   ///Termina dibujar Geofence////
```

**Comment by vicchi** [comment]
See my comment on Issue #254 re: the double-click event.

-Gary

**Comment by icebergdelphi** [comment]
My Geofence Example using Mapstraction: https://github.com/icebergdelphi/Mapstraction-Geofence-Example

Thanks.
