### ISSUE TITLE
I can not see Google V3 Pan Zoom Control, Why?

### ISSUE THREAD

**Issue by icebergdelphi** [mapstraction/mxn#259]
Hi all, i'm working with GoogleV3 map and i remember a few days ago, that i had Pan Zoom toolbar displayed on my Map, but about 3 day ago, i can not see the Googlev3 Pan Zoom Tool Bar again, Why? here is my code:

mapstraction = new mxn.Mapstraction('DivMap','googlev3');
                    mapstraction.addControls({
                        pan: true,
                        zoom: 'large',
                        map_type: false //Diferentes tipos de Mapas
                    });
                    mapstraction.setMapType(mxn.Mapstraction.ROADMAP);

}

Thanks.

**Comment by icebergdelphi** [comment]
Hi again, i got it https://github.com/mapstraction/mxn/issues/253

**Comment by gilesc50** [comment]
Thanks, closing as duplicate of #253
