### ISSUE TITLE
Label Markers

### ISSUE THREAD

**Issue by icebergdelphi** [mapstraction/mxn#260]
Does exist a way to create a Labels markers as next image? Thanks.

![recorrido](https://f.cloud.github.com/assets/3418905/669325/a7849b84-d829-11e2-9f84-4d1f6f63b05c.jpg)

**Comment by gilesc50** [comment]
Hi - can you explain the question please?

**Comment by gilesc50** [comment]
Ah I think this is a duplicate of request #276, so am closing this one.
