### ISSUE TITLE
Broken links in the getting started tutorial page

### ISSUE THREAD

**Issue by doppi** [mapstraction/mxn#267]
The documentation links does not work from the getting started tutorial page:
http://mapstraction.com/tutorial/

For example the link to documentation about "markers" leads to the page:
http://mapstraction.com/tutorial/markers/

That page displays the following message:
"404. There isn't a GitHub Page here."

**Comment by vicchi** [comment]
This should really be an issue in the [`mapstraction.github.com`](https://github.com/mapstraction/mapstraction.github.com) repository, which holds the source for the `mapstraction.com` site, but let's not argue about which repository is the correct one.

You're absolutely right; it looks like the way in which GitHub generates pages via Jekyll has changed slightly of recent and so the tutorial navigation was broken. I've just fixed this and pushed it to the `mapstraction.com` site and it's working again now.
