### ISSUE TITLE
Sanitise mxn.LatLonPoint - remove lng or lon member

### ISSUE THREAD

**Issue by gilesc50** [mapstraction/mxn#272]
Can we sanitise the existence of `lon` and `lng`. I suggest we keep `lon` as it's in the object name mxn.LatLonPoint. There are instances where the `lon` gets set but the `lng` doesn't.

**Comment by vicchi** [comment]
Agreed. The existence of two properties for longitude is laudable but, as we've already seen, fraught with the possibility for errors and mistakes.

This could, possibly, break backwards compatibility if existing implementations rely on the presence of `lng` but as the next release will be a major version increment, this is the one time where we can break compatibility and, providing this is amply publicised in the release notes, I don't see this as a road block to doing this.

**Comment by vicchi** [comment]
Resolved for v3.0; see commit f70cbec3249ab413b18f2b7d8fa1d3f77d2b7b98
