### ISSUE TITLE
Esri click events not working

### ISSUE THREAD

**Issue by Rahlon** [mapstraction/mxn#286]
Click events are not fired with esri, This includes both marker click events and map click events. The esri core library does not bind them.

**Comment by gilesc50** [comment]
Hi, which version of mapstraction and Esri api are you using please?

**Comment by Rahlon** [comment]
Mapstraction: 3.0 esri fixes
Esri: 3.5

**Comment by gilesc50** [comment]
Thanks I'll take a look

**Comment by gilesc50** [comment]
Ok, I've fixed that issue on that branch (Gary - sorry didnt have ant on that pc, so it may have lint errors) I'll migrate the fix to the latest branch as well. 

Please do raise any other issues you find in the esri r3, thanks.

**Comment by vicchi** [comment]
Don't worry. I'll fix any lint issues tomorrow when I refresh the 3.0 branch.
