### ISSUE TITLE
CloudMade: Complete core TODOs

### ISSUE THREAD

**Issue by adamd** [mapstraction/mxn#29]

**Comment by adamd** [comment]
15 TODOs remaining

**Comment by gilesc50** [comment]
Just these 4 to do before we can close this: 
addImageOverlay, addOverlay, addTileLayer, toggleTileLayer

**Comment by gilesc50** [comment]
I can't get to the cloudmade documentation anymore: 
 http://developers.cloudmade.com/projects/show/web-maps-api (note: this URL requires a valid CloudMade account and for you to be logged in under that account)

**Comment by gilesc50** [comment]
Ok so closed this due to issue #278
