### ISSUE TITLE
Bug in icon hover code (google provider)

### ISSUE THREAD

**Issue by thenonsequitur** [mapstraction/mxn#30]
Not sure if this is the best place to submit a bug report, but there seems to be a problem with the icon hover code, starting on line 449 of mxn.google.core.js. The code is:

```
    if(this.hoverIconUrl){
        GEvent.addListener(gmarker, "mouseover", function() {
            gmarker.setImage(this.hoverIconUrl);
        });
        GEvent.addListener(gmarker, "mouseout", function() {
            gmarker.setImage(this.iconUrl);
        });
    }
```

The problem is the "this" reference chances between the test and the callback closures. So when the callbacks are actually called, this.hoverIconUrl and this.iconUrl are both undefined. This can be solved by adding some new references that persist into the closures. Something like this:

```
    if(this.hoverIconUrl){
        var hoverIconUrl = this.hoverIconUrl;
        var iconUrl = this.iconUrl;

        GEvent.addListener(gmarker, "mouseover", function() {
            gmarker.setImage(hoverIconUrl);
        });
        GEvent.addListener(gmarker, "mouseout", function() {
            gmarker.setImage(iconUrl);
        });
    }
```

**Comment by dezfowler** [comment]
Thanks, I've put a fix in. Grab v2.0.9 from the Downloads page.
