### ISSUE TITLE
Here 'KeyboardEvent.keyLocation'' is deprecated

### ISSUE THREAD

**Issue by gilesc50** [mapstraction/mxn#306]
Keep getting this message in the console from here, so we should follow the advice!

'KeyboardEvent.keyLocation'' is deprecated. Please use 'KeyboardEvent.location' instead.

**Comment by vicchi** [comment]
We _have_ followed this advice :-) This is a message coming from the HERE provider code, not our implementation. It needs fixing in HERE's code.
