### ISSUE TITLE
Mapstraction via https

### ISSUE THREAD

**Issue by fsavina** [mapstraction/mxn#307]
The latest stable release url for Mapstraction doesn't work on https

https://mapstraction.com/mxn/build/latest/mxn.js?(openlayers)

any chance of having it activated in the future?

**Comment by vicchi** [comment]
Currently mapstraction.com (and all pages and files from that domain) are served up via GitHub pages, which will only serve up via HTTP; HTTPS isn't supported. At some point in the future, mapstraction.com may move to another host but even then it's doubtful that it'll support HTTPS, mainly down to cost implications (one of the Mapstraction contributors would need to pay for this and it's not cheap to do this).

Unfortunately the bottom line is that as long as Mapstraction remains hosted on GitHub, HTTPS won't be supported and even if it does move to another host, we wouldn't be able to financially support the cost of an SSL certificate in addition to hosting charges.

-Gary

**Comment by fsavina** [comment]
Ok, I understand. I'll try in a different way.
Thank you anyway

Fabio
