### ISSUE TITLE
load polygon features from GeoJSON and get feature info on click event usin mapstraction javascript lib.

### ISSUE THREAD

**Issue by neelsaxena** [mapstraction/mxn#51]
Hello..
plz can anyone solve this problem..
i have to load all polygon features from GeoJSON file and display these on map and also on click/hover of particular polygon should display feature attributes...

Geojson data is like this:

{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "Name": "plot-no 5 0fad", "Descriptio": "ABC", "Contact person": "", "Email ID": "", "Mobile number": "" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 75.889982, 17.712351 ], [ 75.889616, 17.713542 ], [ 75.889807, 17.713600 ], [ 75.889885, 17.713501 ], [ 75.890032, 17.713550 ], [ 75.890067, 17.713658 ], [ 75.890171, 17.713666 ], [ 75.890762, 17.713708 ], [ 75.891047, 17.713716 ], [ 75.891468, 17.713692 ], [ 75.891861, 17.713726 ], [ 75.891948, 17.713701 ], [ 75.891936, 17.712599 ], [ 75.890607, 17.712434 ], [ 75.890330, 17.712359 ], [ 75.889982, 17.712351 ] ] ] } }....

please paste the code.

Thanks,

**Comment by vicchi** [comment]
No reply from anyone in 2 years. Closing as part of a general cleanup of Issues.
