### ISSUE TITLE
Can't disable dragging

### ISSUE THREAD

**Issue by deceze** [mapstraction/mxn#54]
I find it impossible to disable dragging for a GoogleV3 map. None of these have any sort of effect:

```
var map = new mxn.Mapstraction('map', 'googlev3');
map.setOptions({ enableDragging : false });
map.setOption('enableDragging', false);
map.dragging(false);
map.applyOptions();
```

**Comment by cyberhobo** [comment]
May be related to issue 39.

**Comment by brunob** [comment]
I think the bug is there :

https://github.com/mapstraction/mxn/blob/master/source/mxn.googlev3.core.js#L95

This should be this code instead :

myOptions.draggable = this.options.enableDragging;

I'll make pull request in the next days.

++

**Comment by brunob** [comment]
I've tested my proposed correction and found that it's not enough cause cyberhobo was wright. The bug of mxn.util.merge pointed on issue #39 make that the draggable options is set to true despite of map.setOption('enableDragging', false);

mxn.options.enableDragging = false

and 

mxn.maps.googlev3.draggable = true

Commit for fixing enableDragging bug in googlev3 is there : 7c9ad16d42d4d28b1cb1998969ead5ca3502f1e8

**Comment by gilesc50** [comment]
retested on release 3 and this does stop the map from being dragged: map.dragging(false); so closing this issue

**Comment by riklaunim** [comment]
can't make it stop dragging on the "dev" branch code even with the mxn.googlev3.core.js fix.
