### ISSUE TITLE
License.js

### ISSUE THREAD

**Issue by angoca** [mapstraction/mxn#62]
Hi,

I was looking at your code, to check in the files' headers or License file specify clearly the license that Mapstraction uses. Apparently, it is defined under BSD license. However, I found a file called license.js that says "all right reserved" (https://github.com/mapstraction/mxn/blob/master/license.js) and this is the opposite of an Open Source License.
I would like to confirm that all code is Open Source, and if so, then, modify this file, because this creates doubts. Also, a file called LICENSE.txt in the root directory is a good guide for the people to ensure that code is Open.

Thanks.

**Comment by brunob** [comment]
Hi, it's a not opposite to put "all right reserved" mention in the header of files part of an open source projet. Juste look at these ones :

https://trac.gajim.org/browser/src/config.py

http://code.google.com/p/fbug/source/browse/branches/firebug1.9/license.txt

My poor english won't allow me to explain you this legal stuff, but it's a common use on open source projects.

++
