### ISSUE TITLE
MapstractionGeocoder object

### ISSUE THREAD

**Issue by gilalan** [mapstraction/mxn#72]
Hello people, i´m following the examples from book 'map-scripting-101...' and in the page 46 from Chapter 3 i can´t building the map.
I tried sometimes and I discovered where is the error, the error is in the line which calls ' new MapstractionGeocoder(add_point, 'googlev3'); '
I just imported the javascript files that are described in the book:
http://maps.google.com/maps/api/js?sensor=false 
mxn.js
mxn.core.js
googlev3.core.js
mxn.google.geocoder.js
mxn.googlev3.geocoder.js (i imported this one to try but unsuccessfully)

My code is very simple and I verified in the FireBug and i detected that MapstractionGeocoder is undefined. Somebody has any idea?
Thanks in advance.

```
var mapstraction, geocoder;
function create_map() {
    mapstraction = new mxn.Mapstraction('mymap', 'googlev3');
    mapstraction.setCenterAndZoom(new mxn.LatLonPoint(-34.397, 150.644), 7);
    mapstraction.addLargeControls();
    mapstraction.addMapTypeControls();
    geocoder = new MapstractionGeocoder(add_point, 'googlev3');
    // Create address object
    var address = {
        street : "38 Ringold Street",
        locality : "San Francisco",
        region : "CA",
        country : "US"
    };
    geocoder.geocode(address);
}
function add_point(loc) {
    var mk = new mxn.Marker(loc.point);
    mk.setInfoBubble(loc.address);
    mapstraction.addMarker(mk);
    mk.openBubble();
    mapstraction.autoCenterAndZoom();
}
```

<body onload="create_map()">
    <div id="mymap"></div>  
</body>

**Comment by brunob** [comment]
Hi gilalan, you can look at this example file to see how to use geocoder :

https://github.com/mapstraction/mxn/blob/master/examples/googlev3.html

The documentation you're readinf seems to be out of date.

++

**Comment by ravimishra25** [comment]
I have a page with displays 10 markers in an openlayers map used via mapstraction.

I want to load map first then marker one by one say after every second, I tried using window.setTimeout() it loads the map and loads only first marker after that it stops.

var map;
  var lat = new Array() ;
  lat=${latitude};
  var lon= new Array();
  lon=${longitude};
  var oneByOneCounter=0;
  var count=10;
  function initMap(){  
       map = new Mapstraction('mymap','openlayers');
       map.setCenter(new LatLonPoint(0.0,0.0));
       map.addControls({pan: true, zoom:'small', map_type:true});
       renderMarkerOneByOne();
       map.autoCenterAndZoom();
     };

   function renderMarkerOneByOne() {
   if (oneByOneCounter < count) {
       latitude= lat[oneByOneCounter];
       longitude= lon[oneByOneCounter];
       var point = new LatLonPoint(latitude,longitude);
       var marker = new Marker(point);
       var info = "("+(oneByOneCounter+1)+")";
       marker.setInfoBubble(info);
       marker.setHover(true);
       marker.setIcon('icon_green.png', [27,31]);
       map.addMarker(marker);  
       oneByOneCounter++;
       window.setTimeout("renderMarkerOneByOne()", 1000);
     } else {
       oneByOneCounter = 0;
    }
   }

I am not able to figure out where I am doing wrong renderMarkerOneByOne() function executes properly and on putting alert() I can see the marker object is getting created all the time but, for some reason after the first marker gets plotted the other markers are not getting plotted on the map.

Any help or suggestion is welcomed

Thanks

**Comment by brunob** [comment]
Sorry ravimishra25 but your message is off-topic. This issue should be closed and you can open a new one for your problem.

**Comment by ravimishra25** [comment]
I am sorry brunob, I realized it later, I opened a new issue day before yesterday, but, I found solution yesterday after debugging the code

**Comment by brunob** [comment]
Great, happy to know that your problem is solved ;)

**Comment by brunob** [comment]
This issue should be closed...
