### ISSUE TITLE
openlayers addImageOverlay error

### ISSUE THREAD

**Issue by emergingdzns** [mapstraction/mxn#76]
When attempting to add an image overlay using openlayers, Firebug issues a "position is null" error.

The openlayers map displays, but the overlay image does not.

See code below:

``` javascript
    function initialize() {
        // initialise the map with your choice of API
        var mapstraction = new mxn.Mapstraction('map_canvas','openlayers');

        var myPoint = new mxn.LatLonPoint(44.031507,-105.3712465);
        mapstraction.addControls({
            pan: true,
            zoom: 'small',
            map_type: true
        });
        mapstraction.setCenterAndZoom(myPoint, 11);
        mapstraction.addImageOverlay("over","CORDEROAPR11.png",50,43.975458,-105.424392, 44.087556, -105.317911);
        //mapstraction.addSmallControls();    
    }
```

**Comment by emergingdzns** [comment]
The png file I was trying to load is very large (dimensionally and file size) so just as a test, I created a new image in illustrator that just has a single solid color in it and exported to jpg. The dimensions are still 13997px by 10413px but the file size is only 1.6 MB. But I am still getting the error. I really like mapstraction's implementation, but I need to be able to overlay the image.

**Comment by brunob** [comment]
Hi, this problem seem to come from a limitation in openlayers API (the bug don't seem to be due to mapstraction). I've found a post where someone have a similar problem with openlayers API :

http://lists.osgeo.org/pipermail/openlayers-users/2010-February/015982.html

Can you try to load your image only using openlayers API (without mapstration) ? If it don't load, the bug is certainly in OL API, and you can close this issue.

++

**Comment by emergingdzns** [comment]
I was able to load the image in native openlayers. Sadly I wasn't able to use mxn, but I'd very much like to in future versions. Here is the code snippet I used in native OL to load the large image:

```function ll2ol (ll,type) { // abstraction from mxn's toProprietary
            if (type == "lon") {
                var newll = ll \* 20037508.34 / 180;
            } else {
                var newll = Math.log(Math.tan((90 + ll) \* Math.PI / 360)) / (Math.PI / 180);
                newll = newll \* 20037508.34 / 180;
            }
            return newll;  
        }

``````
    imgbounds = new OpenLayers.Bounds(ll2ol(-105.424392,'lon'),ll2ol(43.975458,'lat'),ll2ol(-105.317911,'lon'),ll2ol(44.087556,'lat'));
        var overlay = new OpenLayers.Layer.Image(
        "Aerial View", 
        "/media/mapassets/CORDEROAPR11.jpg", // TO DO: make the url to the image dynamic from db
        imgbounds,
        new OpenLayers.Size(27994, 20832),
        {'isBaseLayer': false, 'alwaysInRange': true}
    );
    layerMapnik = new OpenLayers.Layer.OSM.Mapnik("Open Street Maps",{transparent: true},{buffer:3, tileLoadingDelay: 0,isBaseLayer: true});
    map.addLayers([overlay,layerMapnik]);```
``````

Hope that helps solve the problem.

**Comment by brunob** [comment]
Could you provide us a link to this big image in order to debug your problem ?

**Comment by brunob** [comment]
Hi, are you still having this issue ?

If yes, could you provide us a link to your image ? If no, you can close this issue.

++

**Comment by brunob** [comment]
Since there is no update for this issue for a long time, i think we should close it. Any objection ?

**Comment by gilesc50** [comment]
Likewise
