### ISSUE TITLE
addLargeControls with Google Maps v3 adds small controls

### ISSUE THREAD

**Issue by CIPowell** [mapstraction/mxn#85]
When using addLargeControls on a googlev3 instance of mxn, the small zoom control is added, and not pan control is added.

**Comment by brunob** [comment]
Hi, can't reproduce this bug with last release addLargeControls() works great and show the zoom control and the pan controls.

**Comment by CIPowell** [comment]
Apologies, I missed out an important detail, it only occurs when the map is small (say 500px by 250px), even then it appears to be google maps v3 over-riding mapstraction.

So not a bug! sorry guys.
