### ISSUE TITLE
removeOverlay()

### ISSUE THREAD

**Issue by brunob** [mapstraction/mxn#86]
We can add overlays to the map but it's not possible to remove them. I'm asking myself if we could try implement removeOverlay() function.

Maybe every implementation of addOverlay() should keep urls of overlays added to the map in an array (map.overlays). After that, each provider code could provide a removeOverlay() function and retrieve the right overlay to remove by its url.

What does other people think about this ?

++

**Comment by andreszules** [comment]
I need this feature ... I put a image with addImageOverlay ... but the clic event dont work over the image ... i need the coordenates from the image ... because that i think hide the image for can clic in the map and obtain the coordenates.
