### ISSUE TITLE
removeMarker() should call closeBubble()

### ISSUE THREAD

**Issue by brunob** [mapstraction/mxn#90]
Hi, i'm not sure about this, so i open an issue befoire trying to code this. When a marker had an info bubble opened and if you remove that marker from the map with removeMarker() the info bubble stay opened on the map. I think that we should close this info bublle when the marker is removed.

What do you think of that ?

**Comment by amk221** [comment]
Seconded. There are various abstractions that don't seem to be implemented. I've had to write the following functions to fill in the gaps. This is the sort of thing Mapstraction should be preventing.

<pre>
map.click.addHandler(function() {
    // Close all bubbles when the map is clicked
});

map.markerRemoved.addHandler(function( name, src, args ) {
    // Close this marker's bubble when it is removed from the map
});

map.markerAdded.addHandler(function( name, src, args ) {

    args.marker.click.addHandler(function( name, marker ) {
        // Open this marker's bubble when it is clicked
    });

    args.marker.openInfoBubble.addHandler(function( name, marker ) {
        // Close all bubbles except this one, when a marker is clicked
    });

});
</pre>

**Comment by vicchi** [comment]
Agreed. Do you have an implementation you can share? Otherwise, I'll look at getting this done, hopefully in time for the next release.

**Comment by gilesc50** [comment]
This is already in place on the release 3 branch:

```
Mapstraction.prototype.removeMarker = function(marker) {    
var current_marker;
for(var i = 0; i < this.markers.length; i++){
    current_marker = this.markers[i];
    if(marker == current_marker) {
        marker.closeBubble();
        this.invoker.go('removeMarker', arguments);
        marker.onmap = false;
        this.markers.splice(i, 1);
        this.markerRemoved.fire({'marker': marker});
        break;
    }
}
};
```

So am closing this issue
