### ISSUE TITLE
Inverted iconanchors in OpenLayers

### ISSUE THREAD

**Issue by fabTB** [mapstraction/mxn#94]
In Marker.toProprietary function, the anchor point should be inverted so it can be used in the same way as in other providers.
            if(this.iconAnchor) {
                anchor = new OpenLayers.Pixel(<b>-</b>this.iconAnchor[0], <b>-</b>this.iconAnchor[1]);
            }

**Comment by dezfowler** [comment]
Fixed in 95a459c94b0f7b4acf49ad03b19be888ffd84795
