### ISSUE TITLE
Inexistant function in setCenter, OVI provider

### ISSUE THREAD

**Issue by fabTB** [mapstraction/mxn#95]
In setCenter function, a call is made to setCentre in place of setCenter.

**Comment by andreszules** [comment]
Confirm

File: mxn.ovi.core.js
Line: 229
Original Source: map.setCentre(pt);
Fix: map.setCenter(pt);

**Comment by andreszules** [comment]
https://github.com/mapstraction/mxn/pull/129

**Comment by brunob** [comment]
Tnaks for the fix, it's merged now.
