### ISSUE TITLE
How about Leaflet support?

### ISSUE THREAD

**Issue by palewire** [mapstraction/mxn#97]
Pretty please? ;)

**Comment by pmascari** [comment]
Leaflet would be nice.  I just found a fairly large bug on Cloudmade when on Chrome but when I asked about it they told me they weren't going to fix it because they're working on Leaflet.

**Comment by palewire** [comment]
Interesting. I got started on it here, and I have a basic example with markers and polylines and bubbles and custom icons working. 

https://github.com/datadesk/mxn/blob/master/source/mxn.leaflet.core.js

You put you finger on something I'm unsure about. What is the right way to choose a default tile set? The Leaflet docs use Cloudmade tiles, but those require an API key, and, honestly, one of the chief draws of Leaflet for me is the ability to flip in custom tiles from any source.

So what I've done so far is to not place a default tile set on the map, and require the user to provide a source with addTileLayer, which you can see me do here with the Google tile set.

https://github.com/datadesk/mxn/blob/master/examples/leaflet.html

What do you think?

**Comment by freyfogle** [comment]
Another option would be to use mapquest's OSM tiles as the default? I  don't believe a key is needed

http://developer.mapquest.com/web/products/open

**Comment by palewire** [comment]
Hmm. Okay. In my narrow use case, I'd like to be able to choose which tiles to load at the start, and not have to load a second set or switch after it boots. I'm happy to patch the code to use MapQuest's OSM as the default, but is there a standard in MXN for providing an override at init? Just speculating, I suppose you'd just need to pass in an optional addTileLayer. What say you?

**Comment by pmascari** [comment]
I'm not so much worried about the tiles at this time but rather that all the custom scripting we've done through MXN doesn't go to waste.  We ended up on Cloudmade because they had the friendliest commercial license compared to the other big players.  But their refusal to fix the bug I found in Chrome now has us concerned that we may need to switch to Leaflet.  I will try the script palewire has posted.

**Comment by palewire** [comment]
Great. Is there anyway I can help move it along? Would you like a pull request?

**Comment by pmascari** [comment]
Yes, please submit the request.

**Comment by ajturner** [comment]
This example probably shouldn't use Google Tiles via the tile urls as that would be a violation of their Terms of Service. I would suggest using either OpenStreetMap or you are free to use Acetate (based on OSM) 

http://acetate.geoiq.com/tiles/acetate/preview.html

**Comment by palewire** [comment]
Okay. Does Mapstraction have a standard for creating a map with no tile layer? If I know I want to serve a third-party layer (say, my own custom images) and I'd rather just skip the default OSM layer, sensible as it may be, is there a way to properly override it or turn it off?

**Comment by palewire** [comment]
Took your advice, @ajturner. The example now uses OSM tiles via CloudMade instead of Google Maps.

**Comment by palewire** [comment]
I think we've got it.
